proyecto-final-webconfig/Controllers/ConfigController.cs
using Microsoft.AspNetCore.Mvc;
using proyecto_final_webconfig.Data;
using proyecto_final_webconfig.Models;
using proyecto_final_webconfig.Repository;
using proyecto_final_webconfig.Services;
using System.Diagnostics;

namespace proyecto_final_webconfig.Controllers
{
    public class ConfigController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStatsRepository statsRepository;

        public ConfigController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

proyecto-final-webconfig/Controllers/DeviceController.cs
using Microsoft.AspNetCore.Mvc;
using proyecto_final_webconfig.Data;
using proyecto_final_webconfig.Models;
using proyecto_final_webconfig.Services;
using System.Diagnostics;

namespace proyecto_final_webconfig.Controllers
{
    public class DeviceController : Controller
    {
        private readonly ILogger<DeviceController> _logger;
        private readonly IDevicesService DevicesService;

        public DeviceController(ILogger<DeviceController> logger, IDevicesService DevicesService)
        {
            _logger = logger;
            this.DevicesService = DevicesService;
        }

        public async Task<IActionResult> ListDevices()
        {
            //get all entities from the database Devices
            var Devices = await DevicesService.GetAllUpDevices();

            return View(Devices);
        }

        public async Task<IActionResult> ListBlacklist()
        {
            //get all entities from the database Devices
            var Devices = await DevicesService.GetAllBanDevices();

            return View(Devices);
        }

        public async Task<IActionResult> Details(int id)
        {
            //get all entities from the database Devices
            var singleDevice = await DevicesService.GetDeviceByID(id);

            return View(singleDevice);
        }
        //public async Task<IActionResult> DetailsBlackList(int id)
        //{
        //    //get all entities from the database Devices
        //    var singleDevice = await DevicesService.GetDeviceByID(id);

        //    return View(singleDevice);
        //}


        //MoveToBlacklist
        public async Task<IActionResult> BanDevice(int id)
        {
            //move device to blacklist
            await DevicesService.BanDevice(id);

            return RedirectToAction("ListBlackList");
        }
        public async Task<IActionResult> UnbanDevice(int id)
        {
            await DevicesService.UnbanDevice(id);

            return RedirectToAction("ListBlackList");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

proyecto-final-webconfig/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using proyecto_final_webconfig.Models.Entities;

namespace proyecto_final_webconfig.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(User model)
        {
            if (ModelState.IsValid)
            {
                // Aquí deberías verificar las credenciales del usuario (por ejemplo, en una base de datos)
                // Esto es solo un ejemplo básico, NO es recomendable almacenar contraseñas en texto plano en una aplicación real

                if (model.Username == "admin" && model.Password == "admin")
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, model.Username),
                        // Puedes agregar más claims según tus necesidades
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);


                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity));

                    return RedirectToAction("Index", "Home"); // Redirigir a la página principal después del login
                }

                ModelState.AddModelError(string.Empty, "Credenciales inválidas");
            }

            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

proyecto-final-webconfig/Controllers/MonitoreoController.cs
using Microsoft.AspNetCore.Mvc;
using proyecto_final_webconfig.Data;
using proyecto_final_webconfig.Models;
using proyecto_final_webconfig.Services;
using System.Diagnostics;

namespace proyecto_final_webconfig.Controllers
{
    public class MonitoreoController : Controller
    {
        private readonly ILogger<MonitoreoController> _logger;
        private readonly IEventsService eventsService;

        public MonitoreoController(ILogger<MonitoreoController> logger, IEventsService eventsService)
        {
            _logger = logger;
            this.eventsService = eventsService;
        }

        public async Task<IActionResult> List()
        {
            var events = await eventsService.GetAllRecentsEvents();

            return View(events);
        }

        public async Task<IActionResult> ListByDevice(string mac)
        {
            //TODO: get device for MAC and send ID to view
            ViewBag.IdDevice = 0;

            var events = await eventsService.GetAllRecentsEventsByDevice(mac);

            return View("ListDevice", events);
        }
        public async Task<IActionResult> Details(int id)
        {
            //get all entities from the database events
            var singleEvent = await eventsService.GetEventByID(id);

            return View(singleEvent);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

proyecto-final-webconfig/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Espresso IDS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    @await RenderSectionAsync("Styles", required: false)

</head>
<body style="background-color: rgb(235 233 233);">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark text-white border-bottom box-shadow mb-3 bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand btn btn-secondary text-white" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-cup-hot"></i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Monitoreo" asp-action="List"><i class="bi bi-list-columns-reverse"></i>   Registro de eventos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Device" asp-action="ListDevices"><i class="bi bi-display"></i> Dispositivos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Device" asp-action="ListBlackList"><i class="bi bi-crosshair"></i>   Expulsión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Config" asp-action="Index"><i class="bi bi-wrench"></i>   Configuración</a>
                            </li>
                                
                        }
                            
                    </ul>
                </div>
                <div class="navbar-nav ml-auto">
                    @if(User.Identity.IsAuthenticated){
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white btn btn-outline-secondary rounded-pill px-3" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @User.Identity.Name.ToUpper()
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a asp-controller="Login" asp-action="Index" class="dropdown-item"><i class="bi bi-person-fill"></i> Cerrar sesión </a></li>
                            </ul>
                        </li>
                        <div class="nav-item dropdown login-dropdown">
                            
                        </div>
                    }else
                    {
                        <div class="nav-item dropdown login-dropdown">
                            <a asp-controller="Login" asp-action="Index" class="nav-item nav-link text-white btn btn-outline-secondary rounded-pill px-3"><i class="bi bi-person-fill"></i> Iniciar sesión </a>
                        </div>
                    
                    }

                </div>
            </div>

        </nav>
    </header>
    <div class="container-xl" style="max-width: 1400px">
        <main role="main" class="pb-3 card py-3 px-5">
            @RenderBody()
        </main>
    </div>

    @*  <footer class="border-top footer text-muted">
         <div class="container">
             &copy; 2023 - proyecto_final_webconfig - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
         </div>
     </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@@2.5.3/dist/umd/popper.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>